name: Run Python Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      # Setup Python (faster than using Python container)
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: |
            service/lambdas/requirements.txt
            tests/requirements.txt
      
      - name: Show me file structure
        run: |
          pwd
          ls -l
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r service/lambdas/requirements.txt
          pip install -r tests/requirements.txt
      
      - name: Run tests with pytest
        run: pytest -v --cov