name: Run Python Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJ_DEPS: service/lambdas/requirements.txt
  TEST_DEPS: tests/requirements.txt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      # Setup Python (faster than using Python container)
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: |
            "$PROJ_DEPS"
            "$TEST_DEPS"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "$PROJ_DEPS"
          pip install -r "$TEST_DEPS"
      
      - name: Run tests with pytest
        run: pytest -v --cov